---
apiVersion: v1
data:
  config.json: |- 
    {
      "sink": "{{ .Values.config.sink }}" 
    }
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-configmap
  labels:
    app: {{ template "name" . }}
    chart: {{ printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 }}
    release: "{{.Release.Name}}"
    heritage: "{{.Release.Service}}"
