---
apiVersion: v1
data:
  config.json: |- 
    {
      "sink": "{{ .Values.config.sink }}" 
    }
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-configmap
  labels:
    app: {{ template "eventroutereventrouter.name" . }}
    chart: {{ template "namewithversion" . }}
    release: "{{.Release.Name}}"
    heritage: "{{.Release.Service}}"
